sudo: false
cache: bundler
language: ruby

matrix:
  fast_finish: true
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/Gemfile.rails-5
  - gemfiles/Gemfile.rails-6

before_script:
  - cd spec/dummy && RAILS_ENV=test bundle exec rake db:prepare
