sudo: false
cache: bundler
language: ruby

matrix:
  fast_finish: true
rvm:
  - 2.5
  - 2.6
  - 2.7
gemfile:
  - gemfiles/Gemfile.rails-5
  - gemfiles/Gemfile.rails-6

before_script:
  - "cd spec/dummy && bundle exec rake db:drop db:create db:migrate RAILS_ENV=test"
