sudo: false
cache: bundler
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - rbx-2
gemfile:
  - gemfiles/Gemfile.rails-4
  - gemfiles/Gemfile.rails-5

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
