inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'spec/dummy/bin/*'

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'spec/cocooned/**/*_spec.rb'
    - 'spec/shared_examples/**/*.rb'
